// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProektIntegrirani.Repository;

#nullable disable

namespace ProektIntegrirani.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930021743_AddEtlSyncLog")]
    partial class AddEtlSyncLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("StrengthAway")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthHome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.EtlSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClubsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FixturesLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameweeksLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayersLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PredictionRecalculationQueued")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EtlSyncLogs");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KickoffTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.HasIndex("GameweekId");

                    b.HasIndex("HomeClubId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Gameweek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Gameweeks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.InboundSquadEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("InboundSquadEntries");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Bank")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("FplEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeTransfers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastReportedGameweek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FplEntryId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChanceOfPlaying")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("News")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.PlayerPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExpectedMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedPoints")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("PlayerId", "GameweekId", "ModelType")
                        .IsUnique();

                    b.ToTable("PlayerPredictions");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.SquadPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquadPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ManagerId", "GameweekId", "PlayerId")
                        .IsUnique();

                    b.ToTable("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Fixture", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "AwayClub")
                        .WithMany("AwayFixtures")
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("Fixtures")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "HomeClub")
                        .WithMany("HomeFixtures")
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("Gameweek");

                    b.Navigation("HomeClub");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.InboundSquadEntry", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.ApiClient", "ApiClient")
                        .WithMany("InboundSquadEntries")
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiClient");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ProektIntegrirani.Domain.ValueObjects.PlayerSeasonStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Assists")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Bonus")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly?>("ClubJoinDate")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DefensiveContribution")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("ExpectedAssists")
                                .HasColumnType("REAL");

                            b1.Property<double>("ExpectedGoals")
                                .HasColumnType("REAL");

                            b1.Property<double>("ExpectedGoalsConceded")
                                .HasColumnType("REAL");

                            b1.Property<int>("GoalsScored")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Minutes")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Saves")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Starts")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalPoints")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("YellowCards")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Club");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.PlayerPrediction", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("Predictions")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Player", "Player")
                        .WithMany("Predictions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ProektIntegrirani.Domain.ValueObjects.PointsBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("PlayerPredictionId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Appearance")
                                .HasColumnType("REAL");

                            b1.Property<double>("Assists")
                                .HasColumnType("REAL");

                            b1.Property<double>("Bonus")
                                .HasColumnType("REAL");

                            b1.Property<double>("Cards")
                                .HasColumnType("REAL");

                            b1.Property<double>("CleanSheet")
                                .HasColumnType("REAL");

                            b1.Property<double>("DefensiveContribution")
                                .HasColumnType("REAL");

                            b1.Property<double>("Goals")
                                .HasColumnType("REAL");

                            b1.Property<double>("GoalsConceded")
                                .HasColumnType("REAL");

                            b1.Property<double>("Saves")
                                .HasColumnType("REAL");

                            b1.HasKey("PlayerPredictionId");

                            b1.ToTable("PlayerPredictions");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPredictionId");
                        });

                    b.Navigation("Breakdown")
                        .IsRequired();

                    b.Navigation("Gameweek");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.SquadPick", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("SquadPicks")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Manager", "Manager")
                        .WithMany("SquadPicks")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Player", "Player")
                        .WithMany("SquadPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gameweek");

                    b.Navigation("Manager");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.ApiClient", b =>
                {
                    b.Navigation("InboundSquadEntries");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Club", b =>
                {
                    b.Navigation("AwayFixtures");

                    b.Navigation("HomeFixtures");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Gameweek", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Predictions");

                    b.Navigation("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Manager", b =>
                {
                    b.Navigation("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("SquadPicks");
                });
#pragma warning restore 612, 618
        }
    }
}
