// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProektIntegrirani.Repository;

#nullable disable

namespace ProektIntegrirani.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KickoffTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.HasIndex("GameweekId");

                    b.HasIndex("HomeClubId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Gameweek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Gameweeks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Bank")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("FplEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeTransfers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FplEntryId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChanceOfPlaying")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FplId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("News")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("FplId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.PlayerPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AppearancePoints")
                        .HasColumnType("REAL");

                    b.Property<double>("AssistPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("BonusPoints")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("CardPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("CleanSheetPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("DefensiveContributionPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedPoints")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<double>("GoalPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("GoalsConcededPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("SavePoints")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("PlayerId", "GameweekId", "ModelType")
                        .IsUnique();

                    b.ToTable("PlayerPredictions");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.SquadPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameweekId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquadPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ManagerId", "GameweekId", "PlayerId")
                        .IsUnique();

                    b.ToTable("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Fixture", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "AwayClub")
                        .WithMany("AwayFixtures")
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("Fixtures")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "HomeClub")
                        .WithMany("HomeFixtures")
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("Gameweek");

                    b.Navigation("HomeClub");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.PlayerPrediction", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("Predictions")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Player", "Player")
                        .WithMany("Predictions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gameweek");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.SquadPick", b =>
                {
                    b.HasOne("ProektIntegrirani.Domain.Models.Gameweek", "Gameweek")
                        .WithMany("SquadPicks")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Manager", "Manager")
                        .WithMany("SquadPicks")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProektIntegrirani.Domain.Models.Player", "Player")
                        .WithMany("SquadPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gameweek");

                    b.Navigation("Manager");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Club", b =>
                {
                    b.Navigation("AwayFixtures");

                    b.Navigation("HomeFixtures");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Gameweek", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Predictions");

                    b.Navigation("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Manager", b =>
                {
                    b.Navigation("SquadPicks");
                });

            modelBuilder.Entity("ProektIntegrirani.Domain.Models.Player", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("SquadPicks");
                });
#pragma warning restore 612, 618
        }
    }
}
