<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProektIntegrirani.Domain\ProektIntegrirani.Domain.csproj" />
    <ProjectReference Include="..\ProektIntegrirani.Repository\ProektIntegrirani.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
