<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d0c96e78-202c-43ad-a9dd-be231cce49f4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FplPlanner.Domain\FplPlanner.Domain.csproj" />
    <ProjectReference Include="..\FplPlanner.Repository\FplPlanner.Repository.csproj" />
    <ProjectReference Include="..\FplPlanner.Service\FplPlanner.Service.csproj" />
  </ItemGroup>

</Project>
